# Site settings
title: "Francis Wu, Product Designer"
description: "I'm a product-forward cross-functional designer who translates ambiguity into high-impact systems that turn users into heroes of their workflows."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Profile settings
profile_summary: "I'm a product-forward cross-functional designer who translates ambiguity into high-impact systems that turn users into heroes of their workflows."

# Profile social links
profile_links:
  x_url:                 "https://x.com/thisisfranciswu"
  mastadon_url:          "https://mstdn.ca/@thisisfranciswu"
  linkedin_url:          "https://linkedin.com/in/thisisfranciswu"
  medium_url:            "https://medium.com/@thisisfranciswu"
  threads_url:           "https://www.threads.net/@thisisfranciswu"
  bluesky_url:           "https://bsky.app/profile/thisisfranciswu.bsky.social"
