# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Profile social links
profile_links:
  mastadon_url:          "https://mstdn.ca/@thisisfranciswu"
  linkedin_url:          "https://linkedin.com/in/thisisfranciswu"
  medium_url:            "https://medium.com/@thisisfranciswu"
  threads_url:           "https://www.threads.net/@thisisfranciswu"
  bluesky_url:           "https://bsky.app/profile/thisisfranciswu.bsky.social"
